language: c

env:
  - LUA=lua5.1 LUAVER=5.1
  - LUA=lua5.2 LUAVER=5.2
  - LUA=luajit LUAVER=5.1

# Tool setup.
install:
  - sudo apt-get install -qq lua5.1 liblua5.1-dev
  - sudo apt-get install -qq lua5.2 liblua5.2-dev
  - sudo apt-get install -qq luajit libluajit-5.1-dev
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit
  - git clone git://github.com/fperrad/lua-TestMore.git
  - sudo make -C lua-TestMore install LUAVER="$LUAVER"

# Build and test.
script:
  - make LUAVER="$LUAVER"
  - make LUA="$LUA" test

branches:
  only:
    - master

